### ISSUE TITLE
What is the format of comma separated lists?

### ISSUE THREAD

**Issue by AdriaanJoubert** [mgp25/LocalBitcoins-API#3]
Example:

```
"""
    contacts is a comma-separated list of contact IDs that you want to access in bulk.
    The token owner needs to be either a buyer or seller in the contacts, contacts that do not pass this check are simply not returned.
    A maximum of 50 contacts can be requested at a time.
    The contacts are not returned in any particular order.
    """
    def getContactsInfo(self, contacts):
        return self.sendRequest('/api/contact_info/', {'contacts': contacts}, 'get')
```

Here, does `contacts is a comma-separated list of contact IDs` imply that `contacts` is a string of format `'contact1,contact2,contact3'` and not a Python list (e.g. `['contact1', 'contact2', 'contact3']`)?

**Comment by mgp25** [comment]
@adriaanjoubert i did the API long time ago, but i guess its a Python List.

Regards

**Comment by adriaanjoubert** [comment]
Ok, I'll let you know once I've figured it out 👍

**Comment by adriaanjoubert** [comment]
@mgp25 it appears to be a comma separated string, in fact.
