### ISSUE TITLE
Error with postMessageToContact

### ISSUE THREAD

**Issue by hvahora** [mgp25/LocalBitcoins-API#4]
I would like to preface this message with a thank you for taking the time to read it. I am having trouble implementing the following method from the api. I DO NOT believe it is an error with your code, but rather with how I might be using it. Could you please provide an example of how I can implement the following method?

```python
def postMessageToContact(self, contact_id, message):
return self.sendRequest('/api/contact_message_post/' + contact_id + '/', {'msg': message}, 'post')
```

The website says the method `/api/contact_message_post/`  utilizes an access token of Read+Write. However, I do not know how to implement such an access token. When I use a read access token I get the following error:

```
REQUEST: https://localbitcoins.com/api/contact_message_post/8622821/
PARAMS: {'msg': ''}
METHOD: post
RESPONSE: {"error": {"message": "The HMAC authentication does not have access to this scope.", "error_code": 43}}
```

I also get  similar error when I use a Write access token. I've search all over the internet for advice on this and have had no luck. if you could, it would be greatly appreciated if you could provide a working example of this code working.

Thank you!

**Comment by AdriaanJoubert** [comment]
@hvahora I am having a similar issue. How have you solved this?

**Comment by mgp25** [comment]
Hello,

you need to access here: https://localbitcoins.com/accounts/api/

From there you can create a token using the level of restriction you desire. Remember when creating it, select both `write`  and `read`

Regards
